openapi: 3.0.3
info:
  title: Protherm API
  version: "@project.version@"
  description: Minimal OpenAPI spec for Protherm status dashboard.

servers:
  - url: /protherm
    description: Root path for all Protherm endpoints.

paths:

  /roomControlUnit:
    get:
      summary: Get current Room Control Unit status
      operationId: readRoomControlUnit
      responses:
        '200':
          description: Successfully returned RoomControlUnitDto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomControlUnit'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update Room Control Unit parameters
      operationId: updateRoomControlUnit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomControlUnit'
      responses:
        '200':
          description: Successfully updated
        '400':
          description: Invalid request payload
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /burnerControlUnits/block0:
    get:
      summary: Get Burner Control Unit Block 0 data
      operationId: readBurnerControlUnitBlock0
      responses:
        '200':
          description: Successfully returned BurnerControlUnitBlock0Dto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BurnerControlUnitBlock0'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /burnerControlUnits/block1:
    get:
      summary: Get Burner Control Unit Block 1 data
      operationId: readBurnerControlUnitBlock1
      responses:
        '200':
          description: Successfully returned BurnerControlUnitBlock1Dto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BurnerControlUnitBlock1'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /burnerControlUnits/block2:
    get:
      summary: Get Burner Control Unit Block 2 data
      operationId: readBurnerControlUnitBlock2
      responses:
        '200':
          description: Successfully returned BurnerControlUnitBlock2Dto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BurnerControlUnitBlock2'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heaterController:
    get:
      summary: Get HeaterController data
      operationId: readHeaterController
      responses:
        '200':
          description: Successfully returned HeaterControllerDto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeaterController'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /firingAutomat:
    get:
      summary: Get FiringAutomat data
      operationId: readFiringAutomat
      responses:
        '200':
          description: Successfully returned FiringAutomatDto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FiringAutomat'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /unknowns:
    get:
      summary: Get list of unknown telegrams
      operationId: readUnknowns
      responses:
        '200':
          description: Successfully returned list of UnknownDto
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unknown'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: Error code
          type: integer
          format: int32
        message:
          description: Error message
          type: string

    Protherm:
      type: object
      properties:
        roomControlUnit:
          type: RoomControlUnit
        burnerControlUnitBlock0:
          type: BurnerControlUnitBlock0
        burnerControlUnitBlock1:
          type: BurnerControlUnitBlock1
        burnerControlUnitBlock2:
          type: BurnerControlUnitBlock2
        heaterController:
          type: HeaterController
        firingAutomat:
          type: FiringAutomat

    RoomControlUnit:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    
        leadWaterTargetTemperature:
          type: double
        serviceWaterTargetTemperature:
          type: double
        leadWaterHeatingBlocked:
          type: int
        serviceWaterHeatingBlocked:
          type: int

    BurnerControlUnitBlock0:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    

    BurnerControlUnitBlock1:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    
        leadWaterTemperature:
          type: double
        returnWaterTemperature:
          type: double
        serviceWaterTemperature:
          type: double
        heating:
          type: int
        serviceWater:
          type: int
    
    BurnerControlUnitBlock2:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    
        heating:
          type: int
        serviceWater:
          type: int

    HeaterController:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    
        hotWaterCirculatingPump:
          type: int
    
    FiringAutomat:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    
        internalPump:
          type: int

    Unknown:
      type: object
      properties:
        data:
          type: string
        dateTime:
          type: string
          format: date-time    
    